### ISSUE TITLE
Add model sky RA,dec -> FP transform

### ISSUE THREAD

**Issue by sbailey** [desihub/desimeter#13]
Add transforms between sky RA,dec and focal plane x,y based upon an optics model and instrument configuration, i.e. a blind prediction without using GFA astrometry, using hexapod settings, dateobs, RA, dec (and from which precession, airmass, and hour-angle can be derived).  More sophisticated versions might use air temperature, air pressure, and focal plane temperature.

**Comment by julienguy** [comment]
First version in place (with an intermediate tangent plane coordinate system). But will need refinements.
see `transform.radec2tan` and `transform.tan2fp` .

**Comment by sbailey** [comment]
Implemented in PRs #21 and #22.  closing.
