### ISSUE TITLE
missing attribute meandistance

### ISSUE THREAD

**Issue by joesilber** [desihub/desimeter#162]
When running `analyze_bright_image`, I get the following error in` fvc2fp.py`:

```
Traceback (most recent call last):
  File "/software/products/desimeter-master/bin/analyze_bright_image", line 62, in <module>
    print(transfo.tojson())
  File "/software/products/desimeter-master/py/desimeter/transform/fvc2fp.py", line 91, in tojson
    params['meandistance'] = self.meandistance
AttributeError: 'FVC2FP' object has no attribute 'meandistance'
```

Command to produce this is:
```analyze_bright_image --back-illuminated back1.fits --front-illuminated front1.fits -o pos1.csv```

FITS files to run this example are at:
[front1.fits](https://drive.google.com/file/d/1zo6HkWg_1GFXFdTzmGKug10p66krzpKb/view?usp=sharing)
[back1.fits](https://drive.google.com/file/d/1WrjkCqoxXrjyQOd267JmE2wNW39u3YtI/view?usp=sharing)

**Comment by schlafly** [comment]
Can you verify that
https://github.com/desihub/desimeter/pull/163
addresses this?  The new fvc2fp format had assumed that it would only be asked to read in files that it had created, which was a bad assumption.

**Comment by schlafly** [comment]
Addressed in https://github.com/desihub/desimeter/pull/163, closing.
