### ISSUE TITLE
implement fit_acquistion_exposure using guide catalogs

### ISSUE THREAD

**Issue by julienguy** [desihub/desimeter#24]
Develop a script and routine "fit_acquisition_exposure" that 
 * use as input a guide catalog with centroids in pixel coordinates (x_gfa_meas,y_gfa_meas), matched to GAIA ra dec (for instance `/global/cscratch1/sd/schlafly/desi/gfa_reduce_202001/guide-00038408_catalog-00000.fits`, with table columns `xcentroid,ycentroid,ra_gaia,dec_gaia`)
 * transform ra_gaia,dec_gaia -> x_tan,y_tan using transform.radec2tan
 * x_tan,y_tan -> x_fp,y_fp using transform.tan2fp.tan2fp
 * x_fp,y_fp ->x_gfa_pred, x_gfa_pred using fp2gfa (to be implemented)
* fit a transformation from x_gfa_pred, x_gfa_pred to x_gfa_meas, y_gfa_meas with 
  tel_ra, tel_dec, field_rotation, scale factor and maybe compression along parallactic angle

**Comment by sbailey** [comment]
Implemented in #34 as `desi_fit_guide_star_coordinates`.  Closing.
