### ISSUE TITLE
Duplicate code loading metrology data

### ISSUE THREAD

**Issue by joesilber** [desihub/desimeter#26]
There is duplicate code for loading metrology data in zb.py and poly2d.py.

I suggest moving this to a higher level. Implement in one place directly in the base class.

https://github.com/desihub/desimeter/blob/5926626eb19f944510ec460c99dff6f64eb6f914/py/desimeter/transform/fvc2fp/zb.py#L148-L156

https://github.com/desihub/desimeter/blob/5926626eb19f944510ec460c99dff6f64eb6f914/py/desimeter/transform/fvc2fp/poly2d.py#L121-L129

**Comment by sbailey** [comment]
`desimeter.io.load_metrology()` now provides a common point for looking up the metrology file and loading it, but this hasn't yet been back propagated to other code that was doing the `pkg_resources.resource_filename` etc. lookup.

**Comment by julienguy** [comment]
codes use functions in desimeter.io
