### ISSUE TITLE
Add GFA metrology for petal locations 3 and 7

### ISSUE THREAD

**Issue by sbailey** [desihub/desimeter#33]
DESI-5421 metrology is currently missing GFA data for petals 3 and 7, due to missing measurements that weren't taken in the lab.  Add placeholders to `desimeter/data/fp-metrology-patch.csv` using the average of the metrology from the other petals in petal-local coordinates transformed for petals 3 and 7 offsets and rotations.

**Comment by dkirkby** [comment]
Is there some workaround for this?  I am trying to use `gfa2fp` but failing for GUIDE3 and GUIDE7.  Nominal metrology would be fine.

**Comment by julienguy** [comment]
it's been updated since I think.

**Comment by dkirkby** [comment]
Yes, you are right!  (I was on a branch so didn't see the updates).  Time to close this issue then?

**Comment by julienguy** [comment]
yes
