### ISSUE TITLE
Not able to run desi_fvc_proc on 43046 or 43047.

### ISSUE THREAD

**Issue by julienguy** [desihub/desimeter#37]
Study why desi_fvc_proc failed on 43046 or 43047 at KPNO:
INFO:findfiducials.py:279:findfiducials:matched 0 pinholes from 0 fiducials
metrology not matched.

**Comment by schlafly** [comment]
43046 basically has no light.  43047 has light, but the shutter issues are rather severe.  I haven't looked at enough images to know how typical this is.
https://portal.nersc.gov/project/cosmo/temp/schlafly/fvc-00043047.png

**Comment by schlafly** [comment]
I can't find any fiducials in 43047.  Maybe they were off?

**Comment by sbailey** [comment]
Agreed.  43046 is noise and 43047 doesn't have fiducials illuminated to be able to match to them.

**Comment by sbailey** [comment]
For the record:  FIFs/GIFs seen in 20200119/42311 around the GFA on PETAL_LOC=0:
![image](https://user-images.githubusercontent.com/218471/73019814-308d8500-3dd9-11ea-8e00-0825cf3b76d3.png)
vs. the same region for 20200122/43047:
![image](https://user-images.githubusercontent.com/218471/73019946-76e2e400-3dd9-11ea-8350-08b18b653e54.png)

**Comment by schlafly** [comment]
Thanks.  I thought I should be able to find them at a glance.

**Comment by weaverba137** [comment]
Would it be possible to *catch* errors in this case so that the program fails gracefully with an informative error message?  The output of `desi_fvc_proc` is needed as input for @schlafly 's rotation script, so if one crashes messily, so does the other.

**Comment by schlafly** [comment]
https://github.com/desihub/desimeter/pull/38 intends to address this.  Is returning with a non-zero exit code adequate?  Thanks!

**Comment by weaverba137** [comment]
Will be fixed in #38.
