### ISSUE TITLE
incorrect z=0 assumption?

### ISSUE THREAD

**Issue by joesilber** [desihub/desimeter#60]
When calling `ptl2fp`, with an argument of `zptl=None`, a dummy vector is generated for `ptlz` full of zeros:
https://github.com/desihub/desimeter/blob/f3e2500d70e91ea72b180fb2ce5f6493ecc5b6d2/py/desimeter/transform/ptl2fp.py#L85-L88

But this does not match the curved focal surface. I would have thought we need to instead:
1. Calculate `r_ptl = np.hypot(xptl, yptl)`.
1. Estimate `z_ptl` using a function like `R2Z_lookup()` in `posconstants.py`.
(https://desi.lbl.gov/trac/browser/code/focalplane/plate_control/trunk/petal/posconstants.py#L66)

Easy to add this r2z (and z2r) to the desimeter transforms package if desired.

I might not be understanding some subtlety of how the "ptl" coordinates are meant to be interpreted.

**Comment by julienguy** [comment]
please go ahead and fix this @joesilber . I had been lazy and added this zptl=None default as a short cut to produce some plots.

**Comment by joesilber** [comment]
Ok great will do

**Comment by sbailey** [comment]
Agreed with @julienguy.  This is an oversight / shortcut; nothing subtle.

**Comment by joesilber** [comment]
Closed in PR #59
